import { GameState } from "./game-state";

export enum ComponentType {
    WRITE_PROMPTS = "WRITE_PROMPTS",
    LOCATION_SELECT = "LOCATION_SELECT",
    WRITE_OUTCOMES = "WRITE_OUTCOMES",
    ADVENTURE = "ADVENTURE",
    RITUAL = "RITUAL",
    WRITE_ENDINGS = "WRITE_ENDINGS",
    ENDING = "ENDING",
    VOTING = "VOTING",
    WRITE_LOCATION_PROMPT = "WRITE_LOCATION_PROMPT",
    WRITE_LOCATION_OUTCOMES = "WRITE_LOCATION_OUTCOMES",
    SET_ENCOUNTERS = "SET_ENCOUNTERS",
    WHAT_HAPPENS_HERE = "WHAT_HAPPENS_HERE",
    WHAT_CAN_WE_TRY = "WHAT_CAN_WE_TRY",
    HOW_DOES_THIS_RESOLVE = "HOW_DOES_THIS_RESOLVE",
    MAKE_CHOICE = "MAKE_CHOICE",
    NAVIGATE = "NAVIGATE"
}  

export const ComponentTypeGameStateMap: Record<ComponentType, GameState[]> = {
    [ComponentType.WRITE_PROMPTS]: [GameState.WRITE_PROMPTS, GameState.WRITE_PROMPTS_AGAIN],
    [ComponentType.LOCATION_SELECT]: [GameState.LOCATION_SELECT, GameState.LOCATION_SELECT_AGAIN],
    [ComponentType.WRITE_OUTCOMES]: [GameState.WRITE_OPTIONS, GameState.WRITE_OPTIONS_AGAIN],
    [ComponentType.ADVENTURE]: [GameState.ROUND1, GameState.ROUND2],
    [ComponentType.RITUAL]: [GameState.RITUAL],
    [ComponentType.WRITE_ENDINGS]: [GameState.WRITE_ENDINGS],
    [ComponentType.ENDING]: [GameState.ENDING],
    [ComponentType.VOTING]: [GameState.WHERE_ARE_WE_VOTE, GameState.WHO_ARE_WE_VOTE, GameState.WHAT_IS_COMING_VOTE, GameState.WHAT_ARE_WE_CAPABLE_OF_VOTE, GameState.WHAT_DO_WE_FEAR_VOTE, GameState.WHAT_WILL_BECOME_OF_US_VOTE],
    [ComponentType.WRITE_LOCATION_PROMPT]: [GameState.WHERE_CAN_WE_GO],
    [ComponentType.WRITE_LOCATION_OUTCOMES]: [GameState.WHAT_OCCUPATIONS_ARE_THERE],
    [ComponentType.SET_ENCOUNTERS]: [GameState.SET_ENCOUNTERS, GameState.SET_ENCOUNTERS_VOTING, GameState.SET_ENCOUNTERS_WINNERS],
    [ComponentType.WHAT_HAPPENS_HERE]: [GameState.WHAT_HAPPENS_HERE, GameState.WHAT_HAPPENS_HERE_VOTING, GameState.WHAT_HAPPENS_HERE_WINNER],
    [ComponentType.WHAT_CAN_WE_TRY]: [GameState.WHAT_CAN_WE_TRY, GameState.WHAT_CAN_WE_TRY_VOTING, GameState.WHAT_CAN_WE_TRY_WINNERS],
    [ComponentType.HOW_DOES_THIS_RESOLVE]: [GameState.HOW_DOES_THIS_RESOLVE, GameState.HOW_DOES_THIS_RESOLVE_VOTING, GameState.HOW_DOES_THIS_RESOLVE_WINNERS],
    [ComponentType.MAKE_CHOICE]: [GameState.MAKE_CHOICE, GameState.MAKE_CHOICE_VOTING, GameState.MAKE_CHOICE_WINNER],
    [ComponentType.NAVIGATE]: [GameState.NAVIGATE, GameState.NAVIGATE_VOTING, GameState.NAVIGATE_WINNER],
};