export enum GameState {
  INIT = "INIT",
  START = "START",
  WRITE_PROMPTS = "WRITE_PROMPTS",
  LOCATION_SELECT = "LOCATION_SELECT",
  GENERATE_WRITE_OPTION_AUTHORS = "GENERATE_WRITE_OPTION_AUTHORS",
  WRITE_OPTIONS = "WRITE_OPTIONS",
  ROUND1 = "ROUND1",
  START_PHASE2 = "START_PHASE2",
  WRITE_PROMPTS_AGAIN = "WRITE_PROMPTS_AGAIN",
  LOCATION_SELECT_AGAIN = "LOCATION_SELECT_AGAIN",
  GENERATE_WRITE_OPTION_AUTHORS_AGAIN = "GENERATE_WRITE_OPTION_AUTHORS_AGAIN",
  WRITE_OPTIONS_AGAIN = "WRITE_OPTIONS_AGAIN",
  ROUND2 = "ROUND2",
  RITUAL = "RITUAL",
  WRITE_ENDINGS = "WRITE_ENDINGS",
  FINALE = "FINALE"
}  