export enum GameState {
    INIT = "INIT",
    START = "START",
    WRITE_PROMPTS = "WRITE_PROMPTS",
    WRITE_OPTIONS = "WRITE_OPTIONS",
    ROUND1 = "ROUND1",
    WRITE_PROMPTS_AGAIN = "WRITE_PROMPTS_AGAIN",
    WRITE_OPTIONS_AGAIN = "WRITE_OPTIONS_AGAIN",
    ROUND2 = "ROUND2",
    WRITE_ENDINGS = "WRITE_ENDINGS",
    FINALE = "FINALE"
  }  