name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: your-project-id
          install_components: deploy

      - name: Build Docker image
        run: docker build -t us-east4-docker.pkg.dev/nowhere-af065/nowhere-player-client-repo/nowhere-player-client .

      - name: Push Docker image
        run: docker push us-east4-docker.pkg.dev/nowhere-af065/nowhere-player-client-repo/nowhere-player-client

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy nowhere-player-client \
          --image us-east4-docker.pkg.dev/nowhere-af065/nowhere-player-client-repo/nowhere-player-client \
          --platform managed \
          --region us-east4 \
          --allow-unauthenticated
