name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use your project's Node.js version

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Authenticate Docker to Google Container Registry
      uses: docker/login-action@v2
      with:
        registry: us-east4-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} .
        docker push ${{ secrets.DOCKER_IMAGE_NAME }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy nowhere-player-client \
          --image ${{ secrets.DOCKER_IMAGE_NAME }} \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
